config/routes.rb
Rails.application.routes.draw do
  root to: "clearance_batches#index"
  resources :clearance_batches, only: [:index, :show, :create]
  resources :items, only: [:index]
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  has_many :items

end

app/models/item.rb
class Item < ActiveRecord::Base

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :clearance_batch

  scope :sellable,        -> { where(status: 'sellable') }
  scope :order_by_status, -> { order(:status, created_at: :desc) }
  scope :order_by_batch,  -> { order(clearance_batch_id: :desc, created_at: :desc) }

  def clearance!
    update_attributes!(status: 'clearanced',
                       price_sold: calculate_wholesale_price)
  end

  private

  def calculate_wholesale_price
    price = wholesale_clearance_price
    pants_or_dress? ? price_with_minimum(price, 5) : price_with_minimum(price, 2)
  end

  def wholesale_clearance_price
    style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE
  end

  def pants_or_dress?
    style.type == 'pants' || style.type == 'dresses'
  end

  def price_with_minimum(price, minimum)
    price < minimum ? minimum : price
  end
end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController

  def index
    @clearance_batches = ClearanceBatch.all
  end

  def show
    @clearance_batch = ClearanceBatch.includes(:items).find(params[:id])

    respond_to do |format|
      format.csv { render text: ClearanceBatchReport.generate_report(@clearance_batch) }
    end
  end

  def create
    clearancing_status = process_clearance_batch
    set_flash_message(clearancing_status)
    redirect_to action: :index
  end

  private

  def set_flash_message(clearancing_status)
    clearance_batch = clearancing_status.clearance_batch
    alert_messages  = []

    if clearance_batch.persisted?
      flash[:notice]  = "#{clearance_batch.items.count} items clearanced in batch #{clearance_batch.id}"
    else
      alert_messages << "No new clearance batch was added"
    end

    if clearancing_status.errors.any?
      alert_messages << "#{clearancing_status.errors.count} item ids raised errors and were not clearanced"
      clearancing_status.errors.each {|error| alert_messages << error }
    end

    flash[:alert] = alert_messages.join("<br/>") if alert_messages.any?
  end


  def process_clearance_batch
    if params[:csv_batch_file]
      return clearancing_status = ClearancingService.new.process_file(params[:csv_batch_file].tempfile)
    elsif params[:barcode_batch_string]
      return clearancing_status = ClearancingService.new.process_text_field(params[:barcode_batch_string])
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    group_items
  end

  private

  def group_items
    if params[:group_by] == 'status'
      @items = Item.order_by_status
    elsif params[:group_by] == 'batch'
      @items = Item.order_by_batch
    else
      @items = Item.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_batches/index.html.erb
<h1>Stitch Fix Clearance Tool</h1>
<h2>Clearance Batches</h2>

<%= form_tag(clearance_batches_path, multipart: true, class: 'file-upload-form form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'csv_batch_file', 'Select batch file' %>
    <%= file_field_tag 'csv_batch_file', class: 'form-control' %>
  </div>
  <%= button_tag 'upload batch file', class: 'btn btn-primary' %>
<% end %>

<br>

<%= form_tag(clearance_batches_path, multipart: true, class: 'text-field-form form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'barcode_batch_string', "Scan Barcode ID's" %>
    <%= text_field_tag 'barcode_batch_string' %>
  </div>
  <%= button_tag 'submit barcode ids', class: 'btn btn-primary' %>
<% end %>

<br>

<table class="table table-striped clearance_batches">
  <thead>
    <tr>
      <th>Batch</th>
      <th>Date clearanced</th>
      <th>Number of items clearanced</th>
      <th>Download CSV</th>
    </tr>
  </thead>
  <tbody>
    <%- @clearance_batches.each do |clearance_batch| -%>
      <tr>
        <td><%= "Clearance Batch #{clearance_batch.id}" %></td>
        <td><%= l(clearance_batch.created_at, format: :short) %></td>
        <td><%= clearance_batch.items.count %></td>
        <td><%= link_to "Download Batch Report", clearance_batch_path(id: clearance_batch.id, format: :csv) %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/items/index.html.erb
<h1>Items</h1>

<%= form_tag(items_path, multipart: true, method: :get, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= select_tag(:group_by, options_for_select([['Choose Sort Order', 'none'], ['status', 'status'], ['batch', 'batch']])) %>
  </div>
  <%= button_tag 'Sort', class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped clearance_batches">
  <thead>
    <tr>
      <th>ID</th>
      <th>Size</th>
      <th>Color</th>
      <th>Status</th>
      <th>Price Sold</th>
      <th>Style ID</th>
      <th>Clearance Batch ID</th>
      <th>Sold At</th>
    </tr>
  </thead>
  <tbody>
    <%- @items.each do |item| -%>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.size %></td>
        <td><%= item.color %></td>
        <td><%= item.status %></td>
        <td><%= item.price_sold %></td>
        <td><%= item.style_id %></td>
        <td><%= item.clearance_batch_id %></td>
        <td><%= item.created_at %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
  <%= yield %>
</div>

</body>
</html>